set MATLAB=C:\PROGRA~1\MATLAB\R2019b
"%MINGW_DIR%\bin\sh.exe" --login -c "cd \"%CD%\" && make -f QBot2e_Inverse_Kinematics.mk  EXT_MODE=1 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 SHOW_TIMES=0 STRIPSYMBOLS=0 DEBUG=0 DEBUG_HEAP=0 INCLUDE_MDL_TERMINATE_FCN=1 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DEXT_MODE -DON_TARGET_WAIT_FOR_START=0""
